language: java
sudo: false
cache:
  directories:
    - "$HOME/.m2"
jdk:
  - openjdk13
os:
  - linux
jobs:
  include:
    - stage: Download Deps
      script: "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
    - stage: Compile
      script: "./mvnw compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
    - stage: Test
      matrix:
      include:
      - os: linux
        - jdk: openjdk11
        - jdk: openjdk13
      script: "./mvnw test -B"
    - stage: Build Image
      script: "./mvnw jib:build"
